#!/usr/bin/env python3
"""Build original house symbols through pandid's existing stencil converter.

The source artwork is schematic, with no vendor geometry or certification claim.
"""
import base64
from pathlib import Path
import sys
import xml.etree.ElementTree as ET
import zlib

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from pandid.render.house_artwork import ARTWORK
from mxgraph_to_svg import convert_shape

KINDS = {
    'house.pump.rotary_lobe': ('pump', 'rotary_lobe', {'suction': 'W', 'discharge': 'E'}),
    'house.mbr.membrane_cage': ('membrane_cage', 'default', {'feed': 'W', 'mixed_liquor': 'E', 'permeate': 'N', 'air': 'S'}),
    'house.mbr.airlift': ('airlift', 'default', {'liquid_in': 'S', 'air_in': 'W', 'discharge': 'E'}),
}


def render():
    lines = ['"""Generated by scripts/house_symbols.py; original house schematic artwork."""',
             '', 'from pandid.render.symbols import Symbol', '', '', 'def register_house(registry):']
    for key, (kind, variant, names) in KINDS.items():
        art = ARTWORK[key]
        element = ET.fromstring(art.stencil)
        svg, w, h, _constraints, _aspect = convert_shape(element, stroke_width=4)
        compressor = zlib.compressobj(wbits=-15)
        shape = 'stencil(' + base64.b64encode(compressor.compress(art.stencil.encode()) + compressor.flush()).decode() + ')'
        anchors = {name: (x * art.width / 2, y * art.height / 2) for name, x, y in art.anchors}
        ports = {name: anchors[side] for name, side in names.items()}
        faces = {name: {side: ports[name]} for name, side in names.items()}
        icon = f'<g id="sym_{kind}_{variant}"><g transform="scale(.5)">{svg}</g></g>'
        lines.append(f'    registry.register({kind!r}, Symbol(svg={icon!r}, width={w/2!r}, height={h/2!r}, ports={ports!r}, port_faces={faces!r}, drawio_shape={shape!r}), {variant!r})')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    (ROOT / 'pandid/render/_house_symbols.py').write_text(render())
